#!/usr/bin/env python3
"""
Script to create an enhanced Jupyter notebook with comprehensive analysis comments
for the GMM Health Phenotype Discovery project.

This script adds detailed analysis cells before and after each code cell to provide
contextual understanding of the analysis pipeline.
"""

import json
import os

# Read the original notebook
input_file = 'user_input_files/GMM_Health_Phenotype_Discovery_Final.ipynb'
output_file = 'GMM_Health_Phenotype_Discovery_Final_Enhanced.ipynb'

with open(input_file, 'r') as f:
    notebook = json.load(f)

# Define analysis cells to insert before each code cell
# These are organized by phase analysis
analysis_cells = {
    # Phase 1 - Library Imports Analysis
    0: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Environment and Package Configuration",
            "",
            "### What This Cell Does",
            "This cell establishes the computational environment by importing all necessary Python packages for the GMM health phenotype discovery analysis.",
            "",
            "### Key Components",
            "- **Scientific Stack**: NumPy (numerical computing), Pandas (data manipulation), Scikit-learn (machine learning)",
            "- **Visualization**: Matplotlib and Seaborn for creating publication-quality figures",
            "- **Utilities**: Joblib for model persistence, JSON for configuration management",
            "",
            "### Why These Packages?",
            "- **GaussianMixture**: Scikit-learn's implementation of GMM with support for multiple covariance types",
            "- **StandardScaler**: Essential for GMM as it assumes features are normally distributed",
            "- **Dimensionality Reduction**: PCA and t-SNE for visualizing high-dimensional cluster assignments",
            "",
            "### Configuration Choices",
            "- `pd.set_option('display.max_columns', None)` - Allows viewing all 47 columns without truncation",
            "- `plt.style.use('seaborn-v0_8-whitegrid')` - Academic publication style",
            "- `warnings.filterwarnings('ignore')` - Suppresses non-critical warnings for cleaner output",
            "",
            "### Expected Output",
            "The cell confirms successful package import and displays version information for reproducibility.",
            "Version tracking is crucial for scientific reproducibility and debugging.",
            ""
        ]
    },
    
    # Phase 2 - Project Configuration Analysis
    2: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Project Configuration and Directory Structure",
            "",
            "### What This Cell Does",
            "This cell defines the project structure, creates necessary directories, and establishes utility functions for saving outputs.",
            "",
            "### Directory Structure Explained",
            "- **DATA_DIR**: Contains raw (`data/raw/`) and processed (`data/processed/`) data",
            "- **OUTPUT_DIR**: Central location for all analysis outputs (`output_v2/`)",
            "- **MODELS_DIR**: Stores trained GMM models in organized subdirectories by model type",
            "- **FIGURES_DIR**: Contains all visualization outputs",
            "",
            "### Utility Functions",
            "Three core functions are defined:",
            "1. `save_fig()` - Saves matplotlib figures in PNG, PDF, and SVG formats for flexibility",
            "2. `save_model()` - Persists trained models using joblib for future use",
            "3. `save_data()` - Exports DataFrames and arrays to CSV format",
            "",
            "### Best Practice Implementation",
            "- All directories are created with `exist_ok=True` to prevent errors if they already exist",
            "- Subdirectory paths are organized by model type (baseline, tuned, final) for easy navigation",
            "- Output structure follows the CRISP-DM methodology for data science projects",
            "",
            "### Expected Output",
            "Confirmation of directory creation and successful utility function definition.",
            ""
        ]
    },
    
    # Phase 2 Continued - Data Loading Analysis
    4: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Data Acquisition and Initial Exploration",
            "",
            "### What This Cell Does",
            "This cell loads the NHANES health dataset and performs initial data quality assessment.",
            "",
            "### Dataset Overview",
            "- **Source**: National Health and Nutrition Examination Survey (NHANES)",
            "- **Size**: 5,000 respondents × 47 variables",
            "- **Completeness**: Zero missing values (data has been pre-cleaned)",
            "",
            "### Variable Categories",
            "The 47 variables span six health domains:",
            "1. **Demographics** (6 vars): sex, age, race, education, income",
            "2. **Body Composition** (5 vars): weight, height, BMI, waist circumference",
            "3. **Cardiovascular** (5 vars): systolic/diastolic BP, cholesterol panels",
            "4. **Behavioral** (9 vars): smoking, alcohol, physical activity",
            "5. **Clinical Conditions** (8 vars): arthritis, heart disease, cancer",
            "6. **Mental Health** (10 vars): PHQ-9 depression screening items",
            "",
            "### Data Quality Indicators",
            "- **Missing Values: 0%** - Excellent data quality, no imputation required",
            "- **Numeric Encoding**: Categorical variables (sex, race, education) are already numerically encoded",
            "- **Continuous Variables**: Clinical measurements retain decimal precision",
            "",
            "### First Row Interpretation",
            "The first respondent (ID=1) is a 57-year-old individual with:",
            "- BMI: 21.1 (normal weight range)",
            "- Systolic BP: 146.5 mmHg (elevated)",
            "- PHQ-9 Total: 44 (high depression screening score)",
            "",
            "### Expected Output",
            "Dataset shape confirmation, column listing, and preview of the first 5 rows.",
            ""
        ]
    },
    
    # Phase 3 - Data Quality Assessment Analysis
    6: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Data Quality Assessment",
            "",
            "### What This Cell Does",
            "This cell performs comprehensive data quality checks including missing value analysis, data type verification, and basic statistical summary.",
            "",
            "### Quality Checks Performed",
            "1. **Missing Value Analysis**: Confirms data completeness across all 47 columns",
            "2. **Data Type Verification**: Ensures all features are numeric (required for GMM)",
            "3. **Basic Statistics**: Computes mean, std, min, max for all continuous variables",
            "",
            "### Statistical Summary Insights",
            "- **Age**: Range 20-80 years, mean ~50 (adult population sampling)",
            "- **BMI**: Mean ~29 indicates population-level overweight tendency",
            "- **Systolic BP**: Mean ~126 mmHg within normal-elevated range",
            "- **PHQ-9**: Wide range (0-54) indicates diverse mental health states",
            "",
            "### Data Type Implications",
            "All columns are `int64` or `float64`, which is ideal for GMM. The algorithm:",
            "- Requires numeric input for distance computations",
            "- Benefits from standardized features (handled in Phase 4)",
            "- Works with both discrete and continuous variables",
            "",
            "### Expected Output",
            "- Missing value count (expected: 0)",
            "- Data types summary",
            "- Statistical summary table with counts, mean, std, min, percentiles, max",
            ""
        ]
    },
    
    # Phase 4 - Feature Engineering Analysis
    8: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Feature Engineering and Selection",
            "",
            "### What This Cell Does",
            "This cell prepares the feature matrix by excluding non-predictive columns and creating derived variables for enhanced cluster discrimination.",
            "",
            "### Feature Selection Rationale",
            "**Excluded Columns** (12 total):",
            "- `respondent_id`: Identifier, not predictive",
            "- `sex`, `age`, `race_ethnicity`: Demographic proxies (used later for fairness analysis)",
            "- `education_level`, `income_category`: Socioeconomic factors (potential confounders)",
            "- Derived health categories: `bp_category`, `bmi_category`, `cholesterol_risk`, `glucose_category`",
            "- PHQ-9 individual items (only total score retained to avoid redundancy)",
            "",
            "### Final Feature Matrix",
            "- **34 continuous features** selected for clustering",
            "- **Body metrics**: weight_kg, height_cm, bmi, waist_circumference_cm",
            "- **Cardiovascular**: systolic_bp_mmHg, diastolic_bp_mmHg, lipid panels (total, HDL, LDL)",
            "- **Metabolic**: fasting_glucose_mg_dL, insulin_uU_mL",
            "- **Behavioral**: smoking history, alcohol consumption, physical activity levels",
            "- **Clinical**: 8 binary disease indicators (arthritis, heart failure, etc.)",
            "- **Mental Health**: phq9_total_score (single composite)",
            "",
            "### Why This Feature Set?",
            "- **Clinical Relevance**: All features have established relationships with health outcomes",
            "- **Non-redundant**: PHQ-9 items collapsed to single score to avoid multicollinearity",
            "- **Actionable**: Features represent modifiable risk factors or diagnosable conditions",
            "",
            "### Expected Output",
            "Confirmation of 34 features selected, with feature names listed for verification.",
            ""
        ]
    },
    
    # Phase 5 - Feature Scaling Analysis
    10: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Feature Scaling for GMM Optimization",
            "",
            "### What This Cell Does",
            "This cell applies StandardScaler to normalize all features to zero mean and unit variance, which is essential for GMM performance.",
            "",
            "### Why Scaling Matters for GMM",
            "Gaussian Mixture Models use:",
            "- **Euclidean distance** in the feature space for probability calculations",
            "- **Covariance matrices** that estimate feature correlations",
            "",
            "Without scaling, features with larger magnitudes would dominate:",
            "- Glucose values (~100) would outweigh BMI (~30)",
            "- Waist circumference (~100 cm) would overshadow PHQ-9 scores (~10)",
            "",
            "### StandardScaler Transformation",
            "Formula: X_scaled = (X - μ) / σ",
            "",
            "This ensures:",
            "- All features have mean = 0, std = 1",
            "- Features are normally distributed (GMM assumption)",
            "- Equal contribution to cluster assignment probabilities",
            "",
            "### Scaling Statistics",
            "- **Mean**: Centered to 0 for all features",
            "- **Std Dev**: Standardized to 1 for all features",
            "- **Range**: Features now on comparable scales",
            "",
            "### Expected Output",
            "Confirmation of successful transformation with feature statistics.",
            ""
        ]
    },
    
    # Phase 6 - Model Selection Analysis
    12: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Baseline Model Evaluation",
            "",
            "### What This Cell Does",
            "This cell trains baseline GMM models with varying cluster numbers (1-10) to identify the optimal number of components.",
            "",
            "### Model Selection Methodology",
            "**Why Test Multiple Cluster Numbers?**",
            "- Too few clusters: Miss important population subgroups",
            "- Too many clusters: Overfit noise, reduce generalizability",
            "",
            "**Covariance Types Tested** (via loop):",
            "1. **'full'**: Full covariance matrix (most flexible, most parameters)",
            "2. **'tied'**: Shared covariance across clusters",
            "3. **'diag'**: Diagonal covariance (independent features)",
            "4. **'spherical'**: Single variance per cluster (simplest)",
            "",
            "### Evaluation Metrics",
            "- **BIC (Bayesian Information Criterion)**: Penalizes model complexity, lower is better",
            "- **AIC (Akaike Information Criterion)**: Similar to BIC, lower is better",
            "- **Silhouette Score**: Measures cluster separation (-1 to 1, higher is better)",
            "",
            "### Interpretation Guidelines",
            "- **BIC/AIC**: Look for the 'elbow' - where adding clusters provides diminishing returns",
            "- **Silhouette**: Values >0.5 indicate good separation, 0.26-0.5 is moderate",
            "- **Convergence**: Models that don't converge may have too many clusters",
            "",
            "### Expected Output",
            "Grid search results showing BIC, AIC, and silhouette scores for all parameter combinations.",
            ""
        ]
    },
    
    # Phase 7 - Model Selection Visualization Analysis
    14: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Model Selection Visualization",
            "",
            "### What This Cell Does",
            "This cell creates visualizations to help identify the optimal number of clusters and covariance type.",
            "",
            "### Visualizations Generated",
            "1. **BIC Score Plot**: Shows model complexity vs. fit quality",
            "2. **AIC Score Plot**: Alternative model selection criterion",
            "3. **Silhouette Score Plot**: Cluster quality and separation measure",
            "4. **Metric Comparison**: Side-by-side comparison of all metrics",
            "",
            "### How to Interpret the Plots",
            "**Finding the Optimal K (Number of Clusters)**",
            "- Look for the **minimum BIC/AIC point** (best model fit with complexity penalty)",
            "- The **elbow method**: Where the curve starts flattening out",
            "- **Silhouette peaks**: Points where clusters are most distinct",
            "",
            "**Covariance Type Comparison**",
            "- **Full**: Most flexible, highest BIC penalty",
            "- **Diagonal**: Good balance of flexibility and simplicity",
            "- **Spherical**: Simplest, may underfit complex data",
            "",
            "### Visual Design Choices",
            "- **Multiple subplots**: Allows simultaneous comparison",
            "- **Color coding**: Distinguishes covariance types",
            "- **Grid lines**: Aid in reading exact values",
            "- **High DPI**: Publication-quality resolution (300 DPI)",
            "",
            "### Expected Output",
            "Four-panel figure showing model selection metrics across different cluster numbers.",
            ""
        ]
    },
    
    # Phase 8 - Optimal Model Identification Analysis
    16: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Optimal Model Identification",
            "",
            "### What This Cell Does",
            "This cell identifies and extracts the best performing model configuration based on the grid search results.",
            "",
            "### Selection Criteria",
            "**Primary Criterion: BIC Score**",
            "- BIC balances model fit (log-likelihood) against complexity (number of parameters)",
            "- Preferred over AIC for model selection tasks",
            "- Lower BIC indicates better model",
            "",
            "**Secondary Criteria** (if BIC ties):",
            "- Silhouette score (higher is better)",
            "- Convergence status (must converge)",
            "- Model interpretability",
            "",
            "### Optimal Configuration Details",
            "The best model is determined by:",
            "1. Finding the minimum BIC value from the grid search results",
            "2. Extracting the corresponding number of components and covariance type",
            "3. Recording the associated AIC and silhouette scores",
            "",
            "### Model Complexity Trade-off",
            "Optimal models balance:",
            "- **Underfitting**: Too few clusters miss population structure",
            "- **Overfitting**: Too many clusters capture noise rather than signal",
            "- **Computational Cost**: More clusters = more parameters = longer training",
            "",
            "### Expected Output",
            "Best model parameters (n_components, covariance_type) with associated metrics (BIC, AIC, silhouette).",
            ""
        ]
    },
    
    # Phase 9 - Hyperparameter Tuning Analysis
    18: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Fine-Tuning the Optimal Model",
            "",
            "### What This Cell Does",
            "This cell performs fine-grained hyperparameter tuning around the optimal configuration found in the grid search.",
            "",
            "### Why Fine-Tuning?",
            "The initial grid search provides a starting point, but fine-tuning:",
            "- Tests nearby configurations that might perform better",
            "- Optimizes regularization parameters",
            "- Tests multiple random initializations",
            "",
            "### Hyperparameters Tuned",
            "1. **n_init**: Number of random initializations (1-10)",
            "   - More initializations reduce risk of local optima",
            "   - Trade-off: computational cost vs. solution quality",
            "",
            "2. **reg_covar**: Regularization added to covariance matrix",
            "   - Prevents singular covariance matrices",
            "   - Higher values = more stable, less flexible",
            "",
            "3. **max_iter**: Maximum EM iterations (100-500)",
            "   - Ensures algorithm converges",
            "   - Higher values allow more refinement",
            "",
            "4. **random_state**: For reproducibility",
            "",
            "### Grid Search Parameters",
            "The grid search tests combinations of:",
            "- `n_init`: [1, 2, 5, 10]",
            "- `reg_covar`: [1e-6, 1e-5, 1e-4, 1e-3]",
            "- `max_iter`: [100, 200, 300, 500]",
            "",
            "### Expected Output",
            "Fine-tuned model parameters with improved BIC and AIC scores.",
            ""
        ]
    },
    
    # Phase 10 - Final Model Training Analysis
    20: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Final Model Training and Convergence",
            "",
            "### What This Cell Does",
            "This cell trains the final GMM model with optimized parameters and verifies successful convergence.",
            "",
            "### Final Model Configuration",
            "The optimal model is trained with:",
            "- **n_components**: [NUMBER] clusters (determined by grid search)",
            "- **covariance_type**: [TYPE] (determined by grid search)",
            "- **n_init**: [NUMBER] random initializations",
            "- **reg_covar**: [VALUE] regularization",
            "- **max_iter**: [NUMBER] maximum iterations",
            "",
            "### Convergence Verification",
            "**Convergence Criteria**",
            "- The EM algorithm iteratively alternates between E-step and M-step",
            "- Convergence occurs when log-likelihood change < 1e-6",
            "- The model reports `converged_ = True/False`",
            "",
            "**What Convergence Tells Us**",
            "- **True**: Algorithm found a stable solution",
            "- **False**: May need more iterations or different initialization",
            "",
            "### Model Training Process",
            "1. Initialize cluster means (K-means++ by default)",
            "2. E-step: Calculate posterior probabilities",
            "3. M-step: Update cluster parameters",
            "4. Repeat until convergence or max iterations",
            "",
            "### Expected Output",
            "Final model training confirmation with convergence status and log-likelihood value.",
            ""
        ]
    },
    
    # Phase 11 - Cluster Assignment Analysis
    22: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Cluster Assignment and Membership Probabilities",
            "",
            "### What This Cell Does",
            "This cell assigns each respondent to their most likely cluster and calculates membership probabilities.",
            "",
            "### Cluster Assignment Process",
            "**Maximum A Posteriori (MAP) Assignment**",
            "Each respondent receives a probability of belonging to each cluster. The assigned cluster is:",
            "`cluster = argmax(P(cluster_k | data_i))`",
            "",
            "**Probability Matrix Interpretation**",
            "- Rows: Individual respondents (5,000 samples)",
            "- Columns: Cluster membership probabilities (5 clusters)",
            "- Values: P(cluster_k | individual_i), sum to 1 across rows",
            "",
            "### Key Insights from Probabilities",
            "**High Confidence Assignments** (P > 0.8):",
            "- Individual strongly belongs to one cluster",
            "- Clear phenotypic characterization",
            "",
            "**Low Confidence Assignments** (P < 0.5):",
            "- Individual on cluster boundary",
            "- May represent transition phenotypes",
            "- Important for uncertainty quantification",
            "",
            "### Cluster Size Distribution",
            "The assigned clusters reveal population subgroup sizes:",
            "- Largest cluster: [MAX_COUNT] individuals ([MAX_PCT]%)",
            "- Smallest cluster: [MIN_COUNT] individuals ([MIN_PCT]%)",
            "",
            "### Expected Output",
            "Cluster assignment counts and proportions for each cluster.",
            ""
        ]
    },
    
    # Phase 12 - Uncertainty Quantification Analysis
    24: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Uncertainty Quantification",
            "",
            "### What This Cell Does",
            "This cell quantifies the uncertainty in cluster assignments using maximum probability and entropy measures.",
            "",
            "### Uncertainty Metrics Explained",
            "**1. Maximum Probability (Max Prob)**",
            "- The highest cluster membership probability for each individual",
            "- Range: 0.2 to 1.0 (for 5 clusters)",
            "- Higher values = more certain assignment",
            "",
            "**2. Assignment Entropy**",
            "- Measures uncertainty using Shannon entropy",
            "- Formula: H = -Σ P_k × log(P_k)",
            "- Range: 0 (certain) to log(5) ≈ 1.61 (maximum uncertainty)",
            "",
            "### Confidence Categories",
            "Assignments are categorized by confidence level:",
            "- **High Confidence**: max_prob ≥ 0.8",
            "- **Moderate Confidence**: 0.5 ≤ max_prob < 0.8",
            "- **Low Confidence**: max_prob < 0.5",
            "",
            "### Statistical Summary",
            "- **Mean Max Probability**: [MEAN_PROB]",
            "- **Mean Entropy**: [MEAN_ENTROPY]",
            "- **High Confidence Rate**: [HIGH_CONF_PCT]%",
            "",
            "### Clinical Implications",
            "High uncertainty assignments:",
            "- May represent individuals with mixed phenotypes",
            "- Require additional clinical assessment",
            "- Could benefit from longitudinal follow-up",
            "",
            "### Expected Output",
            "Probability statistics and confidence level distribution counts.",
            ""
        ]
    },
    
    # Phase 13 - PCA Visualization Analysis
    26: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: PCA Visualization of Cluster Structure",
            "",
            "### What This Cell Does",
            "This cell applies Principal Component Analysis (PCA) to reduce the 34-dimensional feature space to 2D for visualization.",
            "",
            "### Dimensionality Reduction Rationale",
            "**Why PCA for Visualization?**",
            "- Humans can only perceive 2D/3D spaces",
            "- 34 dimensions cannot be directly visualized",
            "- PCA preserves global structure and relationships",
            "",
            "**PCA Components Explained**",
            "- **PC1**: Direction of maximum variance in data",
            "- **PC2**: Direction of second maximum variance (orthogonal to PC1)",
            "- Explained variance ratio indicates information retained",
            "",
            "### Visualization Design",
            "**2x2 Subplot Layout**:",
            "1. **Top Left**: Scatter plot of all respondents colored by cluster",
            "2. **Top Right**: Cluster centroids in PC space",
            "3. **Bottom Left**: Individual cluster distributions",
            "4. **Bottom Right**: Confidence ellipses for each cluster",
            "",
            "### Interpretation Guide",
            "- **Well-separated clusters**: Clear visual boundaries",
            "- **Overlapping clusters**: Some phenotypic similarity",
            "- **Ellipse orientation**: Indicates feature correlations",
            "- **Cluster centroids**: Represent 'typical' individuals in each group",
            "",
            "### Expected Output",
            "Four-panel visualization showing cluster structure in reduced dimensionality.",
            ""
        ]
    },
    
    # Phase 13 Continued - t-SNE Analysis
    28: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: t-SNE Non-linear Visualization",
            "",
            "### What This Cell Does",
            "This cell applies t-Distributed Stochastic Neighbor Embedding (t-SNE) for non-linear dimensionality reduction and visualization.",
            "",
            "### t-SNE vs PCA",
            "**PCA Characteristics**",
            "- Linear projection (preserves global structure)",
            "- Fast computation",
            "- Good for initial exploration",
            "",
            "**t-SNE Characteristics**",
            "- Non-linear embedding (preserves local neighborhoods)",
            "- Slower computation",
            "- Better at revealing cluster structure in complex data",
            "",
            "### t-SNE Algorithm Overview",
            "1. **Similarity Calculation**: Measures pairwise similarities in high-D space",
            "2. **Low-D Mapping**: Finds similar configuration in 2D",
            "3. **Gradient Descent**: Minimizes divergence between distributions",
            "",
            "### Parameter Choices",
            "- **perplexity**: 30 (balance between local and global structure)",
            "- **n_components**: 2 (for visualization)",
            "- **random_state**: 42 (reproducibility)",
            "",
            "### Interpretation Tips",
            "- **Cluster tightness**: Densely packed clusters indicate coherent groups",
            "- **Inter-cluster distance**: Large gaps suggest distinct phenotypes",
            "- **Cluster shape**: t-SNE can create artificial shapes; focus on density",
            "",
            "### Expected Output",
            "Side-by-side comparison of PCA and t-SNE visualizations for cluster validation.",
            ""
        ]
    },
    
    # Phase 14 - Cluster Profile Analysis
    30: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Cluster Profile Characterization",
            "",
            "### What This Cell Does",
            "This cell calculates comprehensive statistics for each cluster, characterizing the health phenotypes of each subgroup.",
            "",
            "### Profile Statistics Computed",
            "**Central Tendency**",
            "- Mean values for all 34 features per cluster",
            "- Provides the 'typical' profile for each phenotype",
            "",
            "**Dispersion Measures**",
            "- Standard deviation within each cluster",
            "- Indicates homogeneity of each subgroup",
            "",
            "**Count Statistics**",
            "- Number of individuals in each cluster",
            "- Proportion of total population",
            "",
            "### Key Findings to Look For",
            "**Cluster Differentiation**",
            "- Which clusters have elevated BMI?",
            "- Which clusters show high PHQ-9 scores?",
            "- Which clusters have cardiovascular risk factors?",
            "",
            "**Clinical Interpretation**",
            "- Healthy phenotype: Low risk across all domains",
            "- Metabolic syndrome: High BMI, glucose, BP",
            "- Mental health phenotype: High PHQ-9, normal physical",
            "- Cardiovascular risk: Cholesterol, BP abnormalities",
            "",
            "### Profile Table Structure",
            "Rows: 34 features | Columns: 5 clusters + population mean",
            "Values: Normalized deviation from population mean (z-scores)",
            "",
            "### Expected Output",
            "Detailed cluster profile table with mean values for all features across clusters.",
            ""
        ]
    },
    
    # Phase 15 - Radar Chart Visualization Analysis
    32: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Radar Chart Cluster Profiles",
            "",
            "### What This Cell Does",
            "This cell creates radar (spider) charts to visualize cluster profiles across multiple health dimensions simultaneously.",
            "",
            "### Radar Chart Construction",
            "**Axes Selection**",
            "Key health domains selected:",
            "1. Body Composition (BMI, waist circumference)",
            "2. Blood Pressure (systolic, diastolic)",
            "3. Lipid Profile (total cholesterol, HDL, LDL)",
            "4. Metabolic Markers (glucose, insulin)",
            "5. Physical Activity (vigorous, moderate recreation)",
            "6. Mental Health (PHQ-9 total score)",
            "",
            "**Feature Normalization**",
            "- All features normalized to 0-1 scale for comparable axes",
            "- Population mean centered for reference",
            "",
            "### Interpretation Guide",
            "**Cluster Shape Analysis**",
            "- **Large area**: High values across multiple domains (multimorbidity)",
            "- **Spiky profile**: Extreme values in specific domains",
            "- **Compact profile**: Near-population average (healthy)",
            "",
            "**Shape Descriptions**",
            "- **'Star' shape**: Balanced profile, near population mean",
            "- **'Triangle' shape**: Dominated by one or two health domains",
            "- **'Pentagon' shape**: Elevated across all domains (high risk)",
            "",
            "### Clinical Relevance",
            "Radar charts allow quick visual identification of:",
            "- Target intervention areas per phenotype",
            "- Phenotype-specific health risks",
            "- Cluster differentiation patterns",
            "",
            "### Expected Output",
            "Five individual radar charts (one per cluster) showing distinctive profile shapes.",
            ""
        ]
    },
    
    # Phase 16 - Combined Radar Chart Analysis
    34: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Combined Radar Chart Comparison",
            "",
            "### What This Cell Does",
            "This cell creates a single overlaid radar chart enabling direct comparison of all cluster profiles.",
            "",
            "### Visual Comparison Benefits",
            "**Overlay vs. Individual Charts**",
            "- Individual: Detailed view of one phenotype",
            "- Overlay: Relative comparison across all phenotypes",
            "",
            "**Key Insights from Overlays**",
            "1. **Cluster Separation**: Non-overlapping areas indicate distinct phenotypes",
            "2. **Profile Similarity**: Similar shapes suggest related health states",
            "3. **Trade-offs**: One cluster high in one domain may be low in another",
            "",
            "### Color Coding Strategy",
            "Each cluster assigned a distinct color:",
            "- Visual discrimination between phenotypes",
            "- Consistent with other visualizations",
            "- Publication-ready color palette (Set2)",
            "",
            "### Legend and Interpretation",
            "- Cluster numbers linked to profile characteristics",
            "- Size of each cluster indicated in legend",
            "- Shape area proportional to overall risk level",
            "",
            "### Practical Applications",
            "- **Clinical Decision Support**: Identify at-risk phenotypes",
            "- **Public Health Planning**: Target interventions by phenotype prevalence",
            "- **Patient Stratification**: Assign new patients to phenotype groups",
            "",
            "### Expected Output",
            "Single radar chart with all 5 clusters overlaid for direct profile comparison.",
            ""
        ]
    },
    
    # Phase 17 - Uncertainty Visualization Analysis
    36: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Probability Uncertainty Visualization",
            "",
            "### What This Cell Does",
            "This cell visualizes the distribution of membership probabilities to understand assignment confidence across the population.",
            "",
            "### Probability Distribution Analysis",
            "**Histograms Generated**",
            "1. **Distribution of Max Probabilities**",
            "   - Shows how confident cluster assignments are",
            "   - Peaks near 1.0 indicate high confidence",
            "   - Flat distribution suggests ambiguous assignments",
            "",
            "2. **Entropy Distribution**",
            "   - Uncertainty measure across population",
            "   - Low entropy = certain assignments",
            "   - High entropy = ambiguous assignments",
            "",
            "### Quality Indicators",
            "**Ideal Distribution Characteristics**",
            "- **Max Prob**: Skewed toward 1.0 (many certain assignments)",
            "- **Entropy**: Skewed toward 0 (low uncertainty)",
            "",
            "**Problematic Patterns**",
            "- **Uniform Max Prob**: Random cluster assignments",
            "- **High Mean Entropy**: Overlapping clusters",
            "",
            "### Statistical Summary",
            "- **High Confidence (≥0.8)**: [HIGH_CONF] individuals ([HIGH_CONF_PCT]%)",
            "- **Moderate Confidence (0.5-0.8)**: [MOD_CONF] individuals ([MOD_CONF_PCT]%)",
            "- **Low Confidence (<0.5)**: [LOW_CONF] individuals ([LOW_CONF_PCT]%)",
            "",
            "### Expected Output",
            "Histograms showing probability and entropy distributions with summary statistics.",
            ""
        ]
    },
    
    # Phase 18 - Parallel Coordinates Analysis
    38: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Parallel Coordinates Visualization",
            "",
            "### What This Cell Does",
            "This cell creates parallel coordinates plots to visualize individual patient trajectories across all normalized health features.",
            "",
            "### Parallel Coordinates Explained",
            "**Visual Structure**",
            "- Each vertical axis represents one feature (34 axes)",
            "- Each line represents one individual",
            "- Lines connect feature values across all dimensions",
            "",
            "**Interpretation Guide**",
            "- **Parallel lines**: Similar profiles across features",
            "- **Crossing lines**: Different patterns between features",
            "- **Color coding**: Cluster membership identifies phenotypic groups",
            "",
            "### Why This Visualization?",
            "**Advantages**",
            "- Shows full individual trajectories (not just means)",
            "- Reveals within-cluster heterogeneity",
            "- Identifies outliers and atypical profiles",
            "",
            "**Limitations**",
            "- 34 axes can be visually cluttered",
            "- Random jitter added to reduce overplotting",
            "- Subsampling used for clarity",
            "",
            "### Clinical Insights",
            "Parallel coordinates reveal:",
            "- **Co-occurring patterns**: Do high BMI individuals also have high BP?",
            "- **Profile variability**: How much do individuals within a cluster differ?",
            "- **Outlier identification**: Individuals with unusual combinations",
            "",
            "### Expected Output",
            "Parallel coordinates plot with 34 features, colored by cluster assignment.",
            ""
        ]
    },
    
    # Phase 18 Continued - Cluster Size Analysis
    40: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Cluster Size and Proportion Analysis",
            "",
            "### What This Cell Does",
            "This cell analyzes the distribution of individuals across clusters and creates visualizations of population proportions.",
            "",
            "### Cluster Size Interpretation",
            "**Population Representation**",
            "- **Largest Cluster**: [MAX_COUNT] individuals ([MAX_PCT]%)",
            "- **Smallest Cluster**: [MIN_COUNT] individuals ([MIN_PCT]%)",
            "- **Total Population**: [TOTAL_COUNT] individuals",
            "",
            "**Size Implications**",
            "- **Large clusters**: Common phenotypes in the population",
            "- **Small clusters**: Rare but distinct health states",
            "- **Balanced sizes**: Equal representation across phenotypes",
            "",
            "### Visualization Design",
            "**Bar Chart with Annotations**",
            "- Each bar represents one cluster",
            "- Height = number of individuals",
            "- Labels show count and percentage",
            "- Color coding consistent with other figures",
            "",
            "**Pie Chart Alternative**",
            "- Shows proportional distribution",
            "- Useful for public health planning",
            "- Clearly shows relative sizes",
            "",
            "### Public Health Relevance",
            "Cluster sizes inform:",
            "- **Resource allocation**: Larger clusters need more resources",
            "- **Prevention priorities**: Target common phenotypes first",
            "- **Rare disease identification**: Small clusters may indicate rare conditions",
            "",
            "### Expected Output",
            "Bar chart and pie chart showing cluster size distribution with proportions.",
            ""
        ]
    },
    
    # Phase 19 - Demographic Association Analysis
    42: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Demographic Association and Chi-Square Tests",
            "",
            "### What This Cell Does",
            "This cell tests whether cluster membership is associated with demographic variables using statistical hypothesis testing.",
            "",
            "### Statistical Methodology",
            "**Chi-Square Test of Independence**",
            "- **Null Hypothesis (H0)**: Cluster membership is independent of demographic variable",
            "- **Alternative Hypothesis (H1)**: Cluster membership depends on demographic variable",
            "- **Test Statistic**: χ² = Σ (Observed - Expected)² / Expected",
            "- **Significance Level**: α = 0.05",
            "",
            "### Variables Tested",
            "1. **Sex** (2 categories: Male/Female)",
            "2. **Age Group** (4 categories: 20-39, 40-59, 60-80)",
            "3. **Race/Ethnicity** (Multiple categories)",
            "",
            "### Interpretation Guidelines",
            "**P-value < 0.05**",
            "- Statistically significant association",
            "- Cluster membership varies by demographic group",
            "- May indicate biological or social determinants",
            "",
            "**P-value ≥ 0.05**",
            "- No significant association detected",
            "- Clusters represent health phenotypes independent of demographics",
            "- More generalizable population subgroups",
            "",
            "### Expected Output",
            "Chi-square statistics, p-values, and contingency tables for each demographic variable.",
            ""
        ]
    },
    
    # Phase 19 Continued - Demographic Visualization Analysis
    44: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Demographic Distribution Visualizations",
            "",
            "### What This Cell Does",
            "This cell creates visualizations showing the demographic composition of each cluster.",
            "",
            "### Visualization Types",
            "**1. Stacked Bar Charts**",
            "- Shows proportion of each demographic group within clusters",
            "- Useful for comparing composition across clusters",
            "",
            "**2. Grouped Bar Charts**",
            "- Shows cluster distribution within each demographic group",
            "- Useful for comparing cluster membership rates",
            "",
            "**3. Box Plots**",
            "- Shows distribution of continuous variables (age) by cluster",
            "- Reveals within-cluster variance",
            "",
            "### Key Visual Insights",
            "**Sex Distribution**",
            "- Are certain clusters predominantly male or female?",
            "- This could indicate sex-specific health phenotypes",
            "",
            "**Age Distribution**",
            "- Do clusters represent different life stages?",
            "- Are there age-specific disease patterns?",
            "",
            "**Race/Ethnicity**",
            "- Are clusters equally distributed across groups?",
            "- Could indicate health disparities",
            "",
            "### Fairness Considerations",
            "If clusters show strong demographic associations:",
            "- Consider potential bias in data collection",
            "- Evaluate clinical applicability across groups",
            "- Document limitations and generalizability",
            "",
            "### Expected Output",
            "Multiple visualizations showing demographic composition by cluster.",
            ""
        ]
    },
    
    # Phase 20 - Bivariate Analysis Analysis
    46: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Bivariate Relationship Analysis",
            "",
            "### What This Cell Does",
            "This cell creates pair plots to visualize bivariate relationships between key health features within and across clusters.",
            "",
            "### Pair Plot Construction",
            "**Grid Structure**",
            "- Diagonal: Distribution of each variable (histogram/KDE)",
            "- Off-diagonal: Scatter plots of paired variables",
            "",
            "**Feature Pairs Selected**",
            "- **BMI vs Waist**: Body composition relationship",
            "- **Systolic BP vs Diastolic BP**: Cardiovascular coupling",
            "- **Glucose vs Insulin**: Metabolic syndrome indicators",
            "- **PHQ-9 vs General Health**: Mental-physical health link",
            "",
            "### Bivariate Analysis Insights",
            "**Correlation Patterns**",
            "- **Positive correlation**: Variables increase together",
            "- **Negative correlation**: Inverse relationship",
            "- **No correlation**: Independent variation",
            "",
            "**Cluster Separation**",
            "- Do clusters separate along certain axes?",
            "- Which features best discriminate phenotypes?",
            "- Are there boundary regions between clusters?",
            "",
            "### Interpretation Tips",
            "- **Tight clusters**: Strong phenotypic coherence",
            "- **Overlapping regions**: Transition phenotypes",
            "- **Outliers**: Individuals with unusual combinations",
            "",
            "### Clinical Relevance",
            "Bivariate relationships reveal:",
            "- **Comorbidity patterns**: Which conditions co-occur?",
            "- **Risk factor interactions**: Synergistic effects",
            "- **Targeted screening**: Which combinations indicate high risk?",
            "",
            "### Expected Output",
            "Pair plot matrix showing bivariate relationships colored by cluster.",
            ""
        ]
    },
    
    # Phase 21 - Final Summary Analysis
    48: {
        "cell_type": "markdown",
        "source": [
            "## Analysis: Final Summary and Export",
            "",
            "### What This Cell Does",
            "This cell creates a comprehensive summary of the entire analysis and exports all results for reproducibility and future use.",
            "",
            "### Summary Components",
            "**1. Dataset Summary**",
            "- Total Samples: [N_SAMPLES]",
            "- Features Used: [N_FEATURES]",
            "",
            "**2. Model Configuration**",
            "- Algorithm: Gaussian Mixture Models (GMM)",
            "- Number of Components: [N_CLUSTERS]",
            "- Covariance Type: [COV_TYPE]",
            "",
            "**3. Model Performance**",
            "- BIC Score: [BIC_SCORE]",
            "- AIC Score: [AIC_SCORE]",
            "- Silhouette Score: [SIL_SCORE]",
            "",
            "**4. Cluster Summary**",
            "- Cluster sizes and proportions",
            "- Mean age, BMI, BP per cluster",
            "",
            "**5. Uncertainty Analysis**",
            "- High Confidence: [HIGH_CONF] ([HIGH_CONF_PCT]%)",
            "- Mean Entropy: [MEAN_ENTROPY]",
            "",
            "### Output Files Generated",
            "**Data Files**",
            "- `complete_cluster_assignments.csv`: Full dataset with cluster labels",
            "- `cluster_probabilities.csv`: Membership probabilities per individual",
            "- `detailed_cluster_profiles.csv`: Cluster statistics",
            "",
            "**Model Files**",
            "- `final_gmm_model.joblib`: Trained GMM model for future predictions",
            "",
            "**Visualization Files**",
            "- All figures saved in multiple formats (PNG, PDF, SVG)",
            "",
            "**Report Files**",
            "- `analysis_report.txt`: Text summary of findings",
            "- `validation_metrics.json`: Model quality metrics",
            "- `fairness_analysis.json`: Demographic associations",
            "- `cluster_thresholds.json`: Cluster-specific statistics",
            "",
            "### Reproducibility Checklist",
            "- Random seeds set (random_state=42)",
            "- Version information logged",
            "- All code commented and organized",
            "- Data preprocessing documented",
            "",
            "### Expected Output",
            "Final summary visualization and confirmation of all exported files.",
            ""
        ]
    }
}

# Insert analysis cells before corresponding code cells
new_cells = []
analysis_counter = 0
phase_mapping = {}

# First pass: identify which code cells correspond to which phases
code_cell_count = 0
for cell in notebook['cells']:
    if cell['cell_type'] == 'code':
        code_cell_count += 1
        phase_mapping[code_cell_count] = len(phase_mapping) + 1

# Second pass: build new cells with analysis inserted
code_cell_count = 0
for cell in notebook['cells']:
    if cell['cell_type'] == 'code':
        code_cell_count += 1
        # Add analysis cell before this code cell
        if code_cell_count in analysis_cells:
            new_cells.append(analysis_cells[code_cell_count])
            analysis_counter += 1
    new_cells.append(cell)

# Update the notebook
notebook['cells'] = new_cells

# Save enhanced notebook
with open(output_file, 'w') as f:
    json.dump(notebook, f, indent=1)

print(f"Enhanced notebook saved to: {output_file}")
print(f"Total analysis cells added: {analysis_counter}")
